/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as PlayRouteRouteImport } from './routes/play/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as PlayDemoRouteImport } from './routes/play/demo'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as HomeTeamsRouteRouteImport } from './routes/home/teams/route'
import { Route as PlayGamesIndexRouteImport } from './routes/play/games/index'
import { Route as HomeTeamsIndexRouteImport } from './routes/home/teams/index'
import { Route as PlayGamesSessionIdRouteImport } from './routes/play/games/$sessionId'
import { Route as ApiSupportTicketsRouteImport } from './routes/api/support/tickets'
import { Route as ApiSupportStreamRouteImport } from './routes/api/support/stream'
import { Route as ApiSupportMessagesRouteImport } from './routes/api/support/messages'
import { Route as ApiSupportConfigRouteImport } from './routes/api/support/config'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HomeTeamsTeamIdRouteRouteImport } from './routes/home/teams/$teamId/route'
import { Route as HomeTeamsTeamIdIndexRouteImport } from './routes/home/teams/$teamId/index'
import { Route as HomeTeamsTeamIdSupportRouteImport } from './routes/home/teams/$teamId/support'
import { Route as HomeTeamsTeamIdChatRouteImport } from './routes/home/teams/$teamId/chat'
import { Route as HomeTeamsTeamIdArchiveRouteImport } from './routes/home/teams/$teamId/archive'
import { Route as PlayGamesDecksDeckIdIndexRouteImport } from './routes/play/games/decks/$deckId/index'
import { Route as PlayGamesDecksDeckIdStatsRouteImport } from './routes/play/games/decks/$deckId/stats'
import { Route as HomeTeamsTeamIdBoardBoardIdRouteImport } from './routes/home/teams/$teamId/board.$boardId'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRouteRoute = PlayRouteRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRouteRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const PlayDemoRoute = PlayDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => PlayRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeTeamsRouteRoute = HomeTeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => HomeRouteRoute,
} as any)
const PlayGamesIndexRoute = PlayGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => PlayRouteRoute,
} as any)
const HomeTeamsIndexRoute = HomeTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeTeamsRouteRoute,
} as any)
const PlayGamesSessionIdRoute = PlayGamesSessionIdRouteImport.update({
  id: '/games/$sessionId',
  path: '/games/$sessionId',
  getParentRoute: () => PlayRouteRoute,
} as any)
const ApiSupportTicketsRoute = ApiSupportTicketsRouteImport.update({
  id: '/api/support/tickets',
  path: '/api/support/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportStreamRoute = ApiSupportStreamRouteImport.update({
  id: '/api/support/stream',
  path: '/api/support/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportMessagesRoute = ApiSupportMessagesRouteImport.update({
  id: '/api/support/messages',
  path: '/api/support/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportConfigRoute = ApiSupportConfigRouteImport.update({
  id: '/api/support/config',
  path: '/api/support/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeTeamsTeamIdRouteRoute = HomeTeamsTeamIdRouteRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => HomeTeamsRouteRoute,
} as any)
const HomeTeamsTeamIdIndexRoute = HomeTeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeTeamsTeamIdRouteRoute,
} as any)
const HomeTeamsTeamIdSupportRoute = HomeTeamsTeamIdSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => HomeTeamsTeamIdRouteRoute,
} as any)
const HomeTeamsTeamIdChatRoute = HomeTeamsTeamIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => HomeTeamsTeamIdRouteRoute,
} as any)
const HomeTeamsTeamIdArchiveRoute = HomeTeamsTeamIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => HomeTeamsTeamIdRouteRoute,
} as any)
const PlayGamesDecksDeckIdIndexRoute =
  PlayGamesDecksDeckIdIndexRouteImport.update({
    id: '/games/decks/$deckId/',
    path: '/games/decks/$deckId/',
    getParentRoute: () => PlayRouteRoute,
  } as any)
const PlayGamesDecksDeckIdStatsRoute =
  PlayGamesDecksDeckIdStatsRouteImport.update({
    id: '/games/decks/$deckId/stats',
    path: '/games/decks/$deckId/stats',
    getParentRoute: () => PlayRouteRoute,
  } as any)
const HomeTeamsTeamIdBoardBoardIdRoute =
  HomeTeamsTeamIdBoardBoardIdRouteImport.update({
    id: '/board/$boardId',
    path: '/board/$boardId',
    getParentRoute: () => HomeTeamsTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/play': typeof PlayRouteRouteWithChildren
  '/widget': typeof WidgetRoute
  '/home/teams': typeof HomeTeamsRouteRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/play/demo': typeof PlayDemoRoute
  '/home/': typeof HomeIndexRoute
  '/play/': typeof PlayIndexRoute
  '/home/teams/$teamId': typeof HomeTeamsTeamIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/support/config': typeof ApiSupportConfigRoute
  '/api/support/messages': typeof ApiSupportMessagesRoute
  '/api/support/stream': typeof ApiSupportStreamRoute
  '/api/support/tickets': typeof ApiSupportTicketsRoute
  '/play/games/$sessionId': typeof PlayGamesSessionIdRoute
  '/home/teams/': typeof HomeTeamsIndexRoute
  '/play/games/': typeof PlayGamesIndexRoute
  '/home/teams/$teamId/archive': typeof HomeTeamsTeamIdArchiveRoute
  '/home/teams/$teamId/chat': typeof HomeTeamsTeamIdChatRoute
  '/home/teams/$teamId/support': typeof HomeTeamsTeamIdSupportRoute
  '/home/teams/$teamId/': typeof HomeTeamsTeamIdIndexRoute
  '/home/teams/$teamId/board/$boardId': typeof HomeTeamsTeamIdBoardBoardIdRoute
  '/play/games/decks/$deckId/stats': typeof PlayGamesDecksDeckIdStatsRoute
  '/play/games/decks/$deckId/': typeof PlayGamesDecksDeckIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/widget': typeof WidgetRoute
  '/api/files': typeof ApiFilesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/play/demo': typeof PlayDemoRoute
  '/home': typeof HomeIndexRoute
  '/play': typeof PlayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/support/config': typeof ApiSupportConfigRoute
  '/api/support/messages': typeof ApiSupportMessagesRoute
  '/api/support/stream': typeof ApiSupportStreamRoute
  '/api/support/tickets': typeof ApiSupportTicketsRoute
  '/play/games/$sessionId': typeof PlayGamesSessionIdRoute
  '/home/teams': typeof HomeTeamsIndexRoute
  '/play/games': typeof PlayGamesIndexRoute
  '/home/teams/$teamId/archive': typeof HomeTeamsTeamIdArchiveRoute
  '/home/teams/$teamId/chat': typeof HomeTeamsTeamIdChatRoute
  '/home/teams/$teamId/support': typeof HomeTeamsTeamIdSupportRoute
  '/home/teams/$teamId': typeof HomeTeamsTeamIdIndexRoute
  '/home/teams/$teamId/board/$boardId': typeof HomeTeamsTeamIdBoardBoardIdRoute
  '/play/games/decks/$deckId/stats': typeof PlayGamesDecksDeckIdStatsRoute
  '/play/games/decks/$deckId': typeof PlayGamesDecksDeckIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/play': typeof PlayRouteRouteWithChildren
  '/widget': typeof WidgetRoute
  '/home/teams': typeof HomeTeamsRouteRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/play/demo': typeof PlayDemoRoute
  '/home/': typeof HomeIndexRoute
  '/play/': typeof PlayIndexRoute
  '/home/teams/$teamId': typeof HomeTeamsTeamIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/support/config': typeof ApiSupportConfigRoute
  '/api/support/messages': typeof ApiSupportMessagesRoute
  '/api/support/stream': typeof ApiSupportStreamRoute
  '/api/support/tickets': typeof ApiSupportTicketsRoute
  '/play/games/$sessionId': typeof PlayGamesSessionIdRoute
  '/home/teams/': typeof HomeTeamsIndexRoute
  '/play/games/': typeof PlayGamesIndexRoute
  '/home/teams/$teamId/archive': typeof HomeTeamsTeamIdArchiveRoute
  '/home/teams/$teamId/chat': typeof HomeTeamsTeamIdChatRoute
  '/home/teams/$teamId/support': typeof HomeTeamsTeamIdSupportRoute
  '/home/teams/$teamId/': typeof HomeTeamsTeamIdIndexRoute
  '/home/teams/$teamId/board/$boardId': typeof HomeTeamsTeamIdBoardBoardIdRoute
  '/play/games/decks/$deckId/stats': typeof PlayGamesDecksDeckIdStatsRoute
  '/play/games/decks/$deckId/': typeof PlayGamesDecksDeckIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/play'
    | '/widget'
    | '/home/teams'
    | '/api/files'
    | '/auth/login'
    | '/auth/sign-up'
    | '/play/demo'
    | '/home/'
    | '/play/'
    | '/home/teams/$teamId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/support/config'
    | '/api/support/messages'
    | '/api/support/stream'
    | '/api/support/tickets'
    | '/play/games/$sessionId'
    | '/home/teams/'
    | '/play/games/'
    | '/home/teams/$teamId/archive'
    | '/home/teams/$teamId/chat'
    | '/home/teams/$teamId/support'
    | '/home/teams/$teamId/'
    | '/home/teams/$teamId/board/$boardId'
    | '/play/games/decks/$deckId/stats'
    | '/play/games/decks/$deckId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/widget'
    | '/api/files'
    | '/auth/login'
    | '/auth/sign-up'
    | '/play/demo'
    | '/home'
    | '/play'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/support/config'
    | '/api/support/messages'
    | '/api/support/stream'
    | '/api/support/tickets'
    | '/play/games/$sessionId'
    | '/home/teams'
    | '/play/games'
    | '/home/teams/$teamId/archive'
    | '/home/teams/$teamId/chat'
    | '/home/teams/$teamId/support'
    | '/home/teams/$teamId'
    | '/home/teams/$teamId/board/$boardId'
    | '/play/games/decks/$deckId/stats'
    | '/play/games/decks/$deckId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home'
    | '/play'
    | '/widget'
    | '/home/teams'
    | '/api/files'
    | '/auth/login'
    | '/auth/sign-up'
    | '/play/demo'
    | '/home/'
    | '/play/'
    | '/home/teams/$teamId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/support/config'
    | '/api/support/messages'
    | '/api/support/stream'
    | '/api/support/tickets'
    | '/play/games/$sessionId'
    | '/home/teams/'
    | '/play/games/'
    | '/home/teams/$teamId/archive'
    | '/home/teams/$teamId/chat'
    | '/home/teams/$teamId/support'
    | '/home/teams/$teamId/'
    | '/home/teams/$teamId/board/$boardId'
    | '/play/games/decks/$deckId/stats'
    | '/play/games/decks/$deckId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  PlayRouteRoute: typeof PlayRouteRouteWithChildren
  WidgetRoute: typeof WidgetRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiSupportConfigRoute: typeof ApiSupportConfigRoute
  ApiSupportMessagesRoute: typeof ApiSupportMessagesRoute
  ApiSupportStreamRoute: typeof ApiSupportStreamRoute
  ApiSupportTicketsRoute: typeof ApiSupportTicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/play/demo': {
      id: '/play/demo'
      path: '/demo'
      fullPath: '/play/demo'
      preLoaderRoute: typeof PlayDemoRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/teams': {
      id: '/home/teams'
      path: '/teams'
      fullPath: '/home/teams'
      preLoaderRoute: typeof HomeTeamsRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/play/games/': {
      id: '/play/games/'
      path: '/games'
      fullPath: '/play/games/'
      preLoaderRoute: typeof PlayGamesIndexRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/home/teams/': {
      id: '/home/teams/'
      path: '/'
      fullPath: '/home/teams/'
      preLoaderRoute: typeof HomeTeamsIndexRouteImport
      parentRoute: typeof HomeTeamsRouteRoute
    }
    '/play/games/$sessionId': {
      id: '/play/games/$sessionId'
      path: '/games/$sessionId'
      fullPath: '/play/games/$sessionId'
      preLoaderRoute: typeof PlayGamesSessionIdRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/api/support/tickets': {
      id: '/api/support/tickets'
      path: '/api/support/tickets'
      fullPath: '/api/support/tickets'
      preLoaderRoute: typeof ApiSupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support/stream': {
      id: '/api/support/stream'
      path: '/api/support/stream'
      fullPath: '/api/support/stream'
      preLoaderRoute: typeof ApiSupportStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support/messages': {
      id: '/api/support/messages'
      path: '/api/support/messages'
      fullPath: '/api/support/messages'
      preLoaderRoute: typeof ApiSupportMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support/config': {
      id: '/api/support/config'
      path: '/api/support/config'
      fullPath: '/api/support/config'
      preLoaderRoute: typeof ApiSupportConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/teams/$teamId': {
      id: '/home/teams/$teamId'
      path: '/$teamId'
      fullPath: '/home/teams/$teamId'
      preLoaderRoute: typeof HomeTeamsTeamIdRouteRouteImport
      parentRoute: typeof HomeTeamsRouteRoute
    }
    '/home/teams/$teamId/': {
      id: '/home/teams/$teamId/'
      path: '/'
      fullPath: '/home/teams/$teamId/'
      preLoaderRoute: typeof HomeTeamsTeamIdIndexRouteImport
      parentRoute: typeof HomeTeamsTeamIdRouteRoute
    }
    '/home/teams/$teamId/support': {
      id: '/home/teams/$teamId/support'
      path: '/support'
      fullPath: '/home/teams/$teamId/support'
      preLoaderRoute: typeof HomeTeamsTeamIdSupportRouteImport
      parentRoute: typeof HomeTeamsTeamIdRouteRoute
    }
    '/home/teams/$teamId/chat': {
      id: '/home/teams/$teamId/chat'
      path: '/chat'
      fullPath: '/home/teams/$teamId/chat'
      preLoaderRoute: typeof HomeTeamsTeamIdChatRouteImport
      parentRoute: typeof HomeTeamsTeamIdRouteRoute
    }
    '/home/teams/$teamId/archive': {
      id: '/home/teams/$teamId/archive'
      path: '/archive'
      fullPath: '/home/teams/$teamId/archive'
      preLoaderRoute: typeof HomeTeamsTeamIdArchiveRouteImport
      parentRoute: typeof HomeTeamsTeamIdRouteRoute
    }
    '/play/games/decks/$deckId/': {
      id: '/play/games/decks/$deckId/'
      path: '/games/decks/$deckId'
      fullPath: '/play/games/decks/$deckId/'
      preLoaderRoute: typeof PlayGamesDecksDeckIdIndexRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/play/games/decks/$deckId/stats': {
      id: '/play/games/decks/$deckId/stats'
      path: '/games/decks/$deckId/stats'
      fullPath: '/play/games/decks/$deckId/stats'
      preLoaderRoute: typeof PlayGamesDecksDeckIdStatsRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/home/teams/$teamId/board/$boardId': {
      id: '/home/teams/$teamId/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/home/teams/$teamId/board/$boardId'
      preLoaderRoute: typeof HomeTeamsTeamIdBoardBoardIdRouteImport
      parentRoute: typeof HomeTeamsTeamIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeTeamsTeamIdRouteRouteChildren {
  HomeTeamsTeamIdArchiveRoute: typeof HomeTeamsTeamIdArchiveRoute
  HomeTeamsTeamIdChatRoute: typeof HomeTeamsTeamIdChatRoute
  HomeTeamsTeamIdSupportRoute: typeof HomeTeamsTeamIdSupportRoute
  HomeTeamsTeamIdIndexRoute: typeof HomeTeamsTeamIdIndexRoute
  HomeTeamsTeamIdBoardBoardIdRoute: typeof HomeTeamsTeamIdBoardBoardIdRoute
}

const HomeTeamsTeamIdRouteRouteChildren: HomeTeamsTeamIdRouteRouteChildren = {
  HomeTeamsTeamIdArchiveRoute: HomeTeamsTeamIdArchiveRoute,
  HomeTeamsTeamIdChatRoute: HomeTeamsTeamIdChatRoute,
  HomeTeamsTeamIdSupportRoute: HomeTeamsTeamIdSupportRoute,
  HomeTeamsTeamIdIndexRoute: HomeTeamsTeamIdIndexRoute,
  HomeTeamsTeamIdBoardBoardIdRoute: HomeTeamsTeamIdBoardBoardIdRoute,
}

const HomeTeamsTeamIdRouteRouteWithChildren =
  HomeTeamsTeamIdRouteRoute._addFileChildren(HomeTeamsTeamIdRouteRouteChildren)

interface HomeTeamsRouteRouteChildren {
  HomeTeamsTeamIdRouteRoute: typeof HomeTeamsTeamIdRouteRouteWithChildren
  HomeTeamsIndexRoute: typeof HomeTeamsIndexRoute
}

const HomeTeamsRouteRouteChildren: HomeTeamsRouteRouteChildren = {
  HomeTeamsTeamIdRouteRoute: HomeTeamsTeamIdRouteRouteWithChildren,
  HomeTeamsIndexRoute: HomeTeamsIndexRoute,
}

const HomeTeamsRouteRouteWithChildren = HomeTeamsRouteRoute._addFileChildren(
  HomeTeamsRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeTeamsRouteRoute: typeof HomeTeamsRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeTeamsRouteRoute: HomeTeamsRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface PlayRouteRouteChildren {
  PlayDemoRoute: typeof PlayDemoRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PlayGamesSessionIdRoute: typeof PlayGamesSessionIdRoute
  PlayGamesIndexRoute: typeof PlayGamesIndexRoute
  PlayGamesDecksDeckIdStatsRoute: typeof PlayGamesDecksDeckIdStatsRoute
  PlayGamesDecksDeckIdIndexRoute: typeof PlayGamesDecksDeckIdIndexRoute
}

const PlayRouteRouteChildren: PlayRouteRouteChildren = {
  PlayDemoRoute: PlayDemoRoute,
  PlayIndexRoute: PlayIndexRoute,
  PlayGamesSessionIdRoute: PlayGamesSessionIdRoute,
  PlayGamesIndexRoute: PlayGamesIndexRoute,
  PlayGamesDecksDeckIdStatsRoute: PlayGamesDecksDeckIdStatsRoute,
  PlayGamesDecksDeckIdIndexRoute: PlayGamesDecksDeckIdIndexRoute,
}

const PlayRouteRouteWithChildren = PlayRouteRoute._addFileChildren(
  PlayRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  PlayRouteRoute: PlayRouteRouteWithChildren,
  WidgetRoute: WidgetRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiSupportConfigRoute: ApiSupportConfigRoute,
  ApiSupportMessagesRoute: ApiSupportMessagesRoute,
  ApiSupportStreamRoute: ApiSupportStreamRoute,
  ApiSupportTicketsRoute: ApiSupportTicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
