/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Timestamp;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Timestamp;
  user_id: string;
}

export interface BoardColumns {
  board_id: string;
  id: Generated<string>;
  name: string;
  position: number;
}

export interface Boards {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  team_id: string;
}

export interface CardAssignees {
  card_id: string;
  created_at: Generated<Timestamp>;
  user_id: string;
}

export interface CardAttachments {
  card_id: string;
  created_at: Generated<Timestamp>;
  file_id: string;
}

export interface CardRelations {
  card_id: string;
  created_at: Generated<Timestamp>;
  kind: Generated<string>;
  related_card_id: string;
}

export interface Cards {
  archived_at: Timestamp | null;
  archived_by: string | null;
  archived_origin: string | null;
  column_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: Json | null;
  description_text: Generated<string>;
  id: Generated<string>;
  position: number;
  tags: Generated<string[]>;
  team_id: string;
  title: string;
}

export interface ChatMessageReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  message_id: string;
  user_id: string;
}

export interface ChatMessages {
  body: Json;
  body_text: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  edited_at: Timestamp | null;
  id: Generated<string>;
  room_id: string;
}

export interface ChatRooms {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  owner_id: string | null;
}

export interface Files {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json;
  path: string;
  user_id: string;
}

export interface GameDeckCards {
  deck_id: string;
  description: string | null;
  file_id: string;
  id: Generated<string>;
  position: number;
  title: string;
}

export interface GameDecks {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
}

export interface GameSessionPlayers {
  joined_at: Generated<Timestamp>;
  session_id: string;
  user_id: string;
}

export interface GameSessions {
  card_count: number | null;
  created_at: Generated<Timestamp>;
  deck_id: string;
  finished_at: Timestamp | null;
  host_id: string | null;
  id: Generated<string>;
  kind: Generated<string>;
  started_at: Timestamp | null;
  status: Generated<string>;
  team_id: string | null;
  visibility: Generated<string>;
  winner_card_id: string | null;
}

export interface Sessions {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: Timestamp;
  user_agent: string | null;
  user_id: string;
}

export interface TeamMembers {
  created_at: Generated<Timestamp>;
  role: Generated<string>;
  team_id: string;
  user_id: string;
}

export interface Teams {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
}

export interface Users {
  created_at: Timestamp;
  email: string;
  email_verified: boolean;
  id: string;
  image: string | null;
  name: string;
  updated_at: Timestamp;
}

export interface Verifications {
  created_at: Timestamp | null;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Timestamp | null;
  value: string;
}

export interface VersusMatchups {
  id: Generated<string>;
  left_card_id: string;
  left_votes: Generated<number>;
  position: number;
  resolved_at: Timestamp | null;
  right_card_id: string;
  right_votes: Generated<number>;
  round: number;
  session_id: string;
  status: Generated<string>;
  winner_card_id: string | null;
}

export interface VersusVotes {
  choice: string;
  created_at: Generated<Timestamp>;
  matchup_id: string;
  user_id: string;
}

export interface DB {
  accounts: Accounts;
  board_columns: BoardColumns;
  boards: Boards;
  card_assignees: CardAssignees;
  card_attachments: CardAttachments;
  card_relations: CardRelations;
  cards: Cards;
  chat_message_reactions: ChatMessageReactions;
  chat_messages: ChatMessages;
  chat_rooms: ChatRooms;
  files: Files;
  game_deck_cards: GameDeckCards;
  game_decks: GameDecks;
  game_session_players: GameSessionPlayers;
  game_sessions: GameSessions;
  sessions: Sessions;
  team_members: TeamMembers;
  teams: Teams;
  users: Users;
  verifications: Verifications;
  versus_matchups: VersusMatchups;
  versus_votes: VersusVotes;
}
